version: "3.9"
services:
  gpu:
    build: .
    image: piotrostr/smplverse
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
    command: nvidia-smi && pytest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
