version: "3"
services:
  test:
    build: .
    image: piotrostr/smplverse
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
      - ~/.deepface:/home/root/.deepface
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    command: pytest  --cov=./ --cov-report=html
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
