version: "3"
services:
  runner:
    depends_on:
      - api
    build: .
    image: piotrostr/smplverse
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
      - ~/.deepface:/root/.deepface
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    command: python main.py
    environment:
      - CHECKLIST_API_URL=http://api:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  api:
    build: checklist_api
    ports:
      - "8000:8000"
    volumes:
      - ./checklist_api/app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=8000'
    command: flask run --host=0.0.0.0 --port=8000
