version: "3"
services:
  runner:
    build: .
    image: piotrostr/smplverse
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
      - ~/.deepface:/root/.deepface
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    command: python main.py --headless
    environment:
      - CHECKLIST_API_URL=http://api:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
